### ISSUE TITLE
Check calculation of KL divergence / information

### ISSUE THREAD

**Issue by johnveitch** [johnveitch/cpnest#22]
Want to double-check the calculation for information in the Skilling paper and compare to the KL divergence between prior and posterior.

**Comment by wdpozzo** [comment]
Ok, I started doing the math (see also [this paper](https://academic.oup.com/mnras/article/414/2/1418/977810/On-statistical-uncertainty-in-nested-sampling)) The KL divergence between prior and posterior is given by 
$H = \int dx p(x)log(p(x)/\pi(x))$ with $p(x)$ the posterior and $\pi(x)$ the prior. Apply Bayes' theorem: $p(x) = L(x)\pi(x)/Z$ and substitute in the integrand to obtain $\int dx L(x)\pi(x)/Z log(L(x)/Z)$ which simplifies to 
$H = Z^{-1} \int dx L(x)\pi(x)[log(L(x)) - log Z]$
Change variables from x to X (the prior fraction in the NS language) so that dX = \pi(x)dx, we get
$H = Z^{-1} \int dX L(X)log(L(X)) - log Z$
which we need to discretise.
Will continue later.

**Comment by mattpitkin** [comment]
I should note that my analytical calculation of the KL divergence in #20 is wrong, and when I do it correctly I get consistent values with the output of the nested sampling code (i.e. Skilling's version).

That said, I can't quite replicate why Skilling's version works: if I work through it myself I get the following code for updating the info (starting with two intermediate values `infoK` and `infoM`):
```
self.infoK = exp(oldZ-self.logZ)*self.infoK + exp(Wt-self.logZ)*logL
self.infoM = exp(oldZ-self.logZ)*self.infoM*(self.logZ/oldZ) + exp(Wt-self.logZ)*self.logZ
self.info = self.infoK - self.infoM
```
What this is basically trying to do is calculate the info at each step, using the current evidence value, but also having to remove the fact the the old evidence was used in the previous calculation. However, this seems to give pretty much consistent results with Skilling's version.

**Comment by mattpitkin** [comment]
Here's my scrawled working of this (which may, or may not, make sense!):

![imag0781](https://cloud.githubusercontent.com/assets/1421092/23400122/c3f15efc-fd9a-11e6-88ea-e0aaf8d3502d.jpg)

**Comment by wdpozzo** [comment]
I see, I think we are missing some simple fact. Will work though it again the afternoon and see if I get to Skilling's answer. I remember i did in the past, but I cannot remember how...

**Comment by mattpitkin** [comment]
I've just done another test and my info version from above:
```
self.infoK = exp(oldZ-self.logZ)*self.infoK + exp(Wt-self.logZ)*logL
self.infoM = exp(oldZ-self.logZ)*self.infoM*(self.logZ/oldZ) + exp(Wt-self.logZ)*self.logZ
self.info = self.infoK - self.infoM
```
actually gives identical results to Skilling's version:
```
self.info = exp(Wt - self.logZ)*logL + exp(oldZ - self.logZ)*(self.info + oldZ) - self.logZ
```
So, I'm reasonably happy that it's correct.

**Comment by wdpozzo** [comment]
Ok, that's excellent! I am still going to try and do the math, but I am glad the recovered value of H is correct.

**Comment by wdpozzo** [comment]
Since we got to the bottom of this, at least numerically, I am going to close this issue.
